### ISSUE TITLE
Manuális kód átvizsgálás  + Statikus analízis

### ISSUE THREAD

**Issue by GyoniA** [BME-MIT-IET/iet-hf-2023-reasonable-excuse#1]
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére (GitHub, Gerrit...) + Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarCloud, SpotBugs, VS Code Analyzer, Codacy, Coverity Scan...).

**Comment by kovacsnoi** [comment]
Issue resolved
